resource "aws_api_gateway_rest_api" "api_gw" {
  name                      = "${var.api_gw_name}"
  description               = "${var.api_description}"
  endpoint_configuration {
    types = ["REGIONAL"]
  }
}

resource "aws_api_gateway_vpc_link" "vpc_link" {
  name                      = "${var.vpc_link_name}"
  description               = "VPC link to spinnaker gate NLB generated by terraform armory scripts"
  target_arns               = ["${var.nlb_arn}"]
}

resource "aws_api_gateway_model" "api_gw_model" {
  rest_api_id = "${aws_api_gateway_rest_api.api_gw.id}"
  name = "${var.api_gw_model_name}"
  description = "JSON model to send parameters to spinnaker generated by terraform armory scripts"
  content_type = "application/json"
  schema = "${var.api_gw_model}"
}

resource "aws_api_gateway_request_validator" "validator" {
  name                        = "spin_validator"
  rest_api_id                 = "${aws_api_gateway_rest_api.api_gw.id}"
  validate_request_body       = "${var.api_validate_body}"
  validate_request_parameters = "${var.api_validate_parameters}"
}